version: '3.8' # Make sure to specify the Compose file version

services:
  gsm-server:
    pull_policy: build # Custom key; ensure your tooling supports this
    build:
      context: ./data # Path to the Dockerfile folder
    container_name: gsm_server
    ports:
      - "8080:8080" # HTTP
      - "8443:8443" # HTTPS
      - "162:162/udp" # SNMP
      - "69:69/udp" # TFTP
      - "5900:5900" # Java KVM (iKVM)
    volumes:
      - gsm_data:/opt/gsm/data
    environment:
      - TZ=UTC
    restart: always

volumes:
  gsm_data:
    driver: local
